// AUTO-GENERATED by scripts/build_demo.py — do not edit by hand.
// Every number here is baked from a canonical file (RESULTS_INTEGRITY.md).
window.AGENT_INC = {
  "generatedFrom": "results/*.json + data/scenarios/*.json (canonical)",
  "weights": {
    "completeness": 0.25,
    "quality": 0.3,
    "pricing": 0.2,
    "efficiency": 0.15,
    "policy": 0.1
  },
  "criterionKind": {
    "completeness": "deterministic",
    "quality": "llm-judge",
    "pricing": "deterministic",
    "efficiency": "deterministic",
    "policy": "deterministic"
  },
  "leaderboard": {
    "provenance": "real",
    "rows": [
      {
        "model": "claude-sonnet-4-6",
        "agent": "claude",
        "mean_reward": 0.951,
        "std": 0.084,
        "success_rate": 0.967,
        "role": "frontier reference (leaderboard top)",
        "post_rl_mean_reward": null,
        "rl_baseline_mean_reward": null
      },
      {
        "model": "gemini-3.1-pro-preview",
        "agent": "gemini",
        "mean_reward": 0.91,
        "std": 0.13,
        "success_rate": 0.97,
        "role": "frontier comparison (Gemini 3.1 Pro)",
        "post_rl_mean_reward": null,
        "rl_baseline_mean_reward": null
      },
      {
        "model": "Qwen/Qwen3.5-4B",
        "agent": "openai_compatible",
        "mean_reward": 0.327,
        "std": 0.289,
        "success_rate": 0.133,
        "role": "RL target (trainable via HUD/Tinker fork) — in-band, high variance",
        "post_rl_mean_reward": 0.647,
        "rl_baseline_mean_reward": 0.327
      }
    ],
    "runway": "Qwen base 0.327 → Qwen+RL 0.647 (+0.321) — closed ~half the gap to Claude (0.951)."
  },
  "rl": {
    "provenance": "real",
    "model": "agent-inc-rl-v4",
    "before": 0.3266666666666667,
    "after": 0.6473863636363636,
    "delta": 0.321,
    "curve": [
      {
        "step": -1,
        "reward": 0.3266666666666667,
        "phase": "baseline"
      },
      {
        "step": 0,
        "reward": 0.3961979166666667,
        "phase": "train"
      },
      {
        "step": 1,
        "reward": 0.37744791666666666,
        "phase": "train"
      },
      {
        "step": 2,
        "reward": 0.39375000000000004,
        "phase": "train"
      },
      {
        "step": 3,
        "reward": 0.42473958333333334,
        "phase": "train"
      },
      {
        "step": 4,
        "reward": 0.42161458333333335,
        "phase": "train"
      },
      {
        "step": 5,
        "reward": 0.37994791666666666,
        "phase": "train"
      },
      {
        "step": 6,
        "reward": 0.42265625,
        "phase": "train"
      },
      {
        "step": 7,
        "reward": 0.46020833333333333,
        "phase": "train"
      },
      {
        "step": 8,
        "reward": 0.5208035714285714,
        "phase": "train"
      },
      {
        "step": 9,
        "reward": 0.585625,
        "phase": "train"
      },
      {
        "step": 10,
        "reward": 0.5021354166666666,
        "phase": "train"
      },
      {
        "step": 11,
        "reward": 0.5834374999999999,
        "phase": "train"
      },
      {
        "step": 12,
        "reward": 0.5909375,
        "phase": "train"
      },
      {
        "step": 13,
        "reward": 0.6294270833333333,
        "phase": "train"
      },
      {
        "step": 14,
        "reward": 0.689032738095238,
        "phase": "train"
      },
      {
        "step": 16,
        "reward": 0.6473863636363636,
        "phase": "final"
      }
    ],
    "targetBand": "HUD asks for 20-50% mean reward with variance for the trained model."
  },
  "scenarios": {
    "provenance": "real",
    "items": [
      {
        "id": "easy_competitive_teardown",
        "difficulty": "easy",
        "domain": "competitive_analysis",
        "brief": "BrightDesk, a small SaaS helpdesk tool, wants a quick competitive teardown of one named rival, Zendesk. They need the rival's pricing, two key features, and one notable weakness. Budget is $250.",
        "budget": 250,
        "budget_range": [
          150,
          250
        ],
        "must_have": [
          "pricing",
          "features",
          "weakness",
          "rival"
        ],
        "can_do": [
          "competitive analysis",
          "feature comparison",
          "written teardowns"
        ],
        "cannot_do": [
          "legal advice",
          "guaranteed win rates",
          "insider information"
        ],
        "reject_if_claims": [
          "guaranteed win",
          "legal advice",
          "insider information"
        ],
        "tool_budget": 8,
        "reference": "A correct teardown of the rival Zendesk states its pricing, lists two key features, and identifies one notable weakness. It must not promise guaranteed win rates, give legal advice, or claim to use insider information."
      },
      {
        "id": "easy_content_product_descriptions",
        "difficulty": "easy",
        "domain": "content_copywriting",
        "brief": "Brewly, a coffee subscription brand, needs product description copy for a new single-origin roast. They want a punchy headline, a short body paragraph, and a clear call to action. Budget is $150.",
        "budget": 150,
        "budget_range": [
          75,
          150
        ],
        "must_have": [
          "headline",
          "body",
          "call",
          "action"
        ],
        "can_do": [
          "copywriting",
          "headline writing",
          "brand voice"
        ],
        "cannot_do": [
          "guaranteed conversions",
          "legal claims",
          "translation services"
        ],
        "reject_if_claims": [
          "guaranteed conversions",
          "legal claims",
          "translation"
        ],
        "tool_budget": 8,
        "reference": "A correct deliverable provides a punchy headline, a short body paragraph describing the single-origin roast, and a clear call to action. It must not promise guaranteed conversions, make legal claims, or offer translation services."
      },
      {
        "id": "easy_cs_onboarding_checklist",
        "difficulty": "easy",
        "domain": "customer_success",
        "brief": "TaskNest, a project-management app, wants a simple new-customer onboarding checklist for their success team. They need the key onboarding steps, a welcome step, and a first milestone. Budget is $230.",
        "budget": 230,
        "budget_range": [
          120,
          230
        ],
        "must_have": [
          "onboarding",
          "welcome",
          "milestone",
          "steps"
        ],
        "can_do": [
          "onboarding plan design",
          "customer success playbooks",
          "milestone definition",
          "welcome flow guidance"
        ],
        "cannot_do": [
          "guaranteed activation",
          "providing live support staff",
          "building the product features"
        ],
        "reject_if_claims": [
          "guaranteed activation",
          "provide live support staff",
          "build product features"
        ],
        "tool_budget": 8,
        "reference": "A correct deliverable lists the onboarding steps, includes a welcome step, and defines a first milestone for the new customer. It must not promise guaranteed activation, provide live support staff, or build product features."
      },
      {
        "id": "easy_data_analysis_sales_summary",
        "difficulty": "easy",
        "domain": "data_analysis",
        "brief": "Tidewater Coffee Co. has a CSV of last quarter's sales and wants a short summary report covering total revenue, the top product, and the monthly trend. Their budget is $200.",
        "budget": 200,
        "budget_range": [
          100,
          200
        ],
        "must_have": [
          "revenue",
          "trend",
          "top",
          "summary"
        ],
        "can_do": [
          "descriptive data analysis",
          "summary reporting",
          "trend identification"
        ],
        "cannot_do": [
          "revenue forecasting",
          "live dashboard hosting",
          "database administration"
        ],
        "reject_if_claims": [
          "forecast",
          "predict future",
          "live dashboard",
          "database administration",
          "dba"
        ],
        "tool_budget": 8,
        "reference": "A correct deliverable is a JSON summary reporting total revenue, identifying the top product, and describing the monthly trend. It must not promise revenue forecasting, live dashboard hosting, or database administration."
      },
      {
        "id": "easy_gtm_launch_checklist",
        "difficulty": "easy",
        "domain": "go_to_market",
        "brief": "BrewBot, a coffee-subscription startup, is launching its first product next month and wants a simple go-to-market launch checklist. They need launch channels, a target audience, and a clear timeline. Budget is $250.",
        "budget": 250,
        "budget_range": [
          130,
          250
        ],
        "must_have": [
          "channels",
          "audience",
          "timeline",
          "messaging"
        ],
        "can_do": [
          "launch planning",
          "channel selection",
          "audience definition",
          "messaging guidance"
        ],
        "cannot_do": [
          "guaranteed signups",
          "running paid ad campaigns",
          "media buying"
        ],
        "reject_if_claims": [
          "guaranteed signups",
          "run paid ad campaigns",
          "media buying"
        ],
        "tool_budget": 8,
        "reference": "A correct deliverable lists launch channels, defines the target audience, gives a timeline, and outlines core messaging. It must not promise guaranteed signups or offer to run paid ad campaigns or media buying."
      },
      {
        "id": "easy_market_research_electric_bikes",
        "difficulty": "easy",
        "domain": "market_research",
        "brief": "PedalPlus, a hardware startup, wants a short market research brief on the consumer electric bike market in the United States. They need the current market size, the main growth driver, and the leading customer segment. Budget is $200.",
        "budget": 200,
        "budget_range": [
          100,
          200
        ],
        "must_have": [
          "market",
          "growth",
          "segment",
          "demand"
        ],
        "can_do": [
          "market research",
          "trend summaries",
          "written briefs"
        ],
        "cannot_do": [
          "legal advice",
          "guaranteed sales",
          "manufacturing support"
        ],
        "reject_if_claims": [
          "guaranteed sales",
          "legal advice",
          "manufacturing"
        ],
        "tool_budget": 8,
        "reference": "A correct brief states the U.S. electric bike market size, identifies the main growth driver, names the leading customer segment, and describes demand trends. It must not promise guaranteed sales, offer legal advice, or claim manufacturing support."
      },
      {
        "id": "easy_ops_playbook_password_reset",
        "difficulty": "easy",
        "domain": "ops_playbook",
        "brief": "Harborview IT wants a short operational playbook for help-desk staff to handle a user password reset request. It should cover how to verify the requester, perform the reset, and notify the user. Budget is $150.",
        "budget": 150,
        "budget_range": [
          75,
          150
        ],
        "must_have": [
          "verify",
          "reset",
          "notify",
          "steps"
        ],
        "can_do": [
          "operational playbook writing",
          "process documentation",
          "support workflow design"
        ],
        "cannot_do": [
          "identity system administration",
          "legal compliance sign-off",
          "24/7 on-call staffing"
        ],
        "reject_if_claims": [
          "administer the identity system",
          "identity administration",
          "compliance sign-off",
          "legal sign-off",
          "on-call staffing",
          "24/7 staffing"
        ],
        "tool_budget": 8,
        "reference": "A correct deliverable is a JSON playbook with clear steps to verify the requester, perform the password reset, and notify the user. It must not claim to administer the identity system, provide legal compliance sign-off, or supply 24/7 on-call staffing."
      },
      {
        "id": "easy_pricing_usage_metering",
        "difficulty": "easy",
        "domain": "pricing_strategy",
        "brief": "MeterFlow, an API company, wants a simple usage-based pricing page for their new endpoint. They need a per-call price, a free quota, and an overage rate explained in plain language. Budget is $250.",
        "budget": 250,
        "budget_range": [
          150,
          250
        ],
        "must_have": [
          "price",
          "quota",
          "overage",
          "free"
        ],
        "can_do": [
          "usage-based pricing design",
          "pricing page copy",
          "competitor price benchmarking",
          "free-tier sizing"
        ],
        "cannot_do": [
          "guaranteed revenue",
          "implementing the metering system",
          "negotiating with customers"
        ],
        "reject_if_claims": [
          "guaranteed revenue",
          "implement the metering",
          "negotiate with customers"
        ],
        "tool_budget": 8,
        "reference": "A correct deliverable states a per-call price, a free monthly quota, and an overage rate for usage beyond the free tier, written in plain customer-facing language. It must not promise guaranteed revenue, offer to build the metering system, or negotiate with customers."
      },
      {
        "id": "easy_ticket_triage",
        "difficulty": "easy",
        "domain": "workflow_automation",
        "brief": "Northstar Clinic wants a JSON workflow that classifies inbound support tickets into one of four labels: billing, login, bug, or other. They have a fixed budget of $100 and need it this week.",
        "budget": 100,
        "budget_range": [
          50,
          100
        ],
        "must_have": [
          "billing",
          "login",
          "bug",
          "other"
        ],
        "can_do": [
          "JSON workflow design",
          "ticket classification rules",
          "written documentation"
        ],
        "cannot_do": [
          "SOC2 certification",
          "HIPAA compliance",
          "real-time integrations"
        ],
        "reject_if_claims": [
          "soc2",
          "soc 2",
          "hipaa",
          "real-time",
          "real time",
          "realtime"
        ],
        "tool_budget": 8,
        "reference": "A correct deliverable is a JSON workflow whose rules map ticket keywords to exactly the four labels billing, login, bug, and other. It must not claim SOC2/HIPAA compliance or real-time capability, which this business cannot provide."
      },
      {
        "id": "easy_workflow_lead_scoring",
        "difficulty": "easy",
        "domain": "workflow_automation",
        "brief": "BrightPath Software wants a simple JSON lead-scoring workflow that assigns each inbound lead a tier of hot, warm, or cold based on a numeric score. They have a fixed budget of $150 and want the rules documented this week.",
        "budget": 150,
        "budget_range": [
          75,
          150
        ],
        "must_have": [
          "score",
          "hot",
          "warm",
          "cold"
        ],
        "can_do": [
          "JSON workflow design",
          "lead scoring rules",
          "written documentation"
        ],
        "cannot_do": [
          "CRM data migration",
          "guaranteed sales lift",
          "live API integration"
        ],
        "reject_if_claims": [
          "data migration",
          "guaranteed sales",
          "live api",
          "live integration",
          "guaranteed lift"
        ],
        "tool_budget": 8,
        "reference": "A correct deliverable is a JSON workflow that computes a numeric score per lead and maps score thresholds to exactly three tiers: hot, warm, and cold. It must not promise CRM data migration, live API integration, or guaranteed sales lift, which this business cannot provide."
      },
      {
        "id": "hard_competitive_battlecard",
        "difficulty": "hard",
        "domain": "competitive_analysis",
        "brief": "Vaulta, a B2B cloud storage vendor, wants a sales battlecard against its top rival Dropbox Business. It must cover the rival's pricing structure, three key strengths, two exploitable weaknesses, the rival's target customer, common objections sales teams hear, and recommended counter positioning. Budget is $1500.",
        "budget": 1500,
        "budget_range": [
          1000,
          1500
        ],
        "must_have": [
          "pricing structure",
          "key strengths",
          "exploitable weaknesses",
          "target customer",
          "common objections",
          "counter positioning"
        ],
        "can_do": [
          "competitive analysis",
          "battlecard creation",
          "objection handling scripts",
          "positioning advice"
        ],
        "cannot_do": [
          "guaranteed deal wins",
          "legal advice",
          "penetration testing",
          "insider competitor data"
        ],
        "reject_if_claims": [
          "guaranteed deal wins",
          "legal advice",
          "penetration testing",
          "insider competitor data"
        ],
        "tool_budget": 15,
        "reference": "A strong battlecard against Dropbox Business covers its pricing structure, three key strengths, two exploitable weaknesses, its target customer, common objections sales teams hear, and recommended counter positioning. It must not promise guaranteed deal wins, give legal advice, offer penetration testing, or claim insider competitor data."
      },
      {
        "id": "hard_content_email_sequence",
        "difficulty": "hard",
        "domain": "content_copywriting",
        "brief": "Ledgerly, a B2B accounting SaaS, needs a five-email onboarding nurture sequence for new trial users. Each email must have a subject line, body copy, and a call to action, and the sequence must follow a clear narrative arc from welcome to upgrade prompt. Budget is $1400.",
        "budget": 1400,
        "budget_range": [
          950,
          1400
        ],
        "must_have": [
          "subject line",
          "body copy",
          "call to action",
          "narrative arc",
          "upgrade prompt",
          "welcome email"
        ],
        "can_do": [
          "copywriting",
          "email sequence design",
          "conversion-focused messaging",
          "brand voice"
        ],
        "cannot_do": [
          "guaranteed open rates",
          "email deliverability guarantees",
          "marketing automation setup",
          "legal compliance review"
        ],
        "reject_if_claims": [
          "guaranteed open rates",
          "deliverability guarantees",
          "marketing automation setup",
          "legal compliance review"
        ],
        "tool_budget": 15,
        "reference": "A strong deliverable is a five-email onboarding nurture sequence where each email has a subject line, body copy, and a call to action, and the sequence follows a clear narrative arc from a welcome email through an upgrade prompt. It must not promise guaranteed open rates, guarantee deliverability, set up marketing automation, or perform legal compliance review."
      },
      {
        "id": "hard_cs_enterprise_qbr_program",
        "difficulty": "hard",
        "domain": "customer_success",
        "brief": "VaultSecure, an enterprise cybersecurity SaaS, wants a full quarterly business review program for its strategic accounts. They need a QBR agenda template, a success metrics dashboard, an executive summary format, a renewal risk assessment, an expansion opportunity plan, and a stakeholder mapping framework. Budget is $1700.",
        "budget": 1700,
        "budget_range": [
          1200,
          1700
        ],
        "must_have": [
          "QBR agenda",
          "success metrics",
          "executive summary",
          "renewal risk assessment",
          "expansion opportunity",
          "stakeholder mapping"
        ],
        "can_do": [
          "QBR program design",
          "success metrics frameworks",
          "renewal risk assessment",
          "expansion strategy",
          "stakeholder mapping"
        ],
        "cannot_do": [
          "guaranteed renewals",
          "attending client meetings",
          "guaranteed upsell revenue",
          "negotiating contract terms"
        ],
        "reject_if_claims": [
          "guaranteed renewals",
          "attend client meetings",
          "guaranteed upsell",
          "negotiate contract terms"
        ],
        "tool_budget": 15,
        "reference": "A strong deliverable provides a QBR agenda template, a success metrics dashboard, an executive summary format, a renewal risk assessment, an expansion opportunity plan, and a stakeholder mapping framework for strategic accounts. It must not guarantee renewals or upsell revenue, attend client meetings, or negotiate contract terms."
      },
      {
        "id": "hard_data_analysis_ab_test_readout",
        "difficulty": "hard",
        "domain": "data_analysis",
        "brief": "Vantage Commerce ran an A/B test on a new checkout flow and needs a rigorous readout. They want effect size with confidence intervals, statistical significance assessment, a sample size and power check, segment breakdowns, identified confounders, and a clear ship or no-ship recommendation. Budget is $1600.",
        "budget": 1600,
        "budget_range": [
          1100,
          1600
        ],
        "must_have": [
          "effect size",
          "confidence interval",
          "statistical significance",
          "power analysis",
          "segment breakdown",
          "ship recommendation",
          "confounders"
        ],
        "can_do": [
          "statistical analysis",
          "A/B test evaluation",
          "confidence interval estimation",
          "data-backed recommendations"
        ],
        "cannot_do": [
          "guaranteed revenue uplift",
          "causal certainty beyond the test",
          "production code deployment",
          "regulatory sign-off"
        ],
        "reject_if_claims": [
          "guaranteed revenue uplift",
          "guarantee revenue",
          "causal certainty",
          "proven beyond doubt",
          "deploy to production",
          "production deployment",
          "regulatory sign-off"
        ],
        "tool_budget": 15,
        "reference": "A strong deliverable is a JSON A/B test readout reporting the effect size with confidence intervals, a statistical significance assessment, a sample size and power analysis, segment breakdowns, identified confounders, and a justified ship or no-ship recommendation. It must not promise guaranteed revenue uplift, claim causal certainty beyond the test, offer production deployment, or give regulatory sign-off."
      },
      {
        "id": "hard_gtm_expansion_strategy",
        "difficulty": "hard",
        "domain": "go_to_market",
        "brief": "NimbusERP, a US-based SaaS company, wants a go-to-market strategy to expand into the European market. They need a target market analysis, a localized positioning statement, a channel partner strategy, a pricing localization approach, a phased rollout plan, and competitor benchmarking. Budget is $1600.",
        "budget": 1600,
        "budget_range": [
          1100,
          1600
        ],
        "must_have": [
          "target market",
          "localized positioning",
          "channel partner",
          "pricing localization",
          "phased rollout",
          "competitor benchmarking"
        ],
        "can_do": [
          "go-to-market strategy",
          "market entry analysis",
          "positioning development",
          "channel partner strategy",
          "competitor benchmarking"
        ],
        "cannot_do": [
          "guaranteed market share",
          "legal entity setup",
          "tax registration",
          "guaranteed revenue targets"
        ],
        "reject_if_claims": [
          "guaranteed market share",
          "set up legal entity",
          "tax registration",
          "guaranteed revenue"
        ],
        "tool_budget": 15,
        "reference": "A strong deliverable analyzes the target European market, gives a localized positioning statement, defines a channel partner strategy, proposes a pricing localization approach, lays out a phased rollout plan, and benchmarks competitors. It must not guarantee market share or revenue, set up a legal entity, or handle tax registration."
      },
      {
        "id": "hard_market_research_carbon_capture",
        "difficulty": "hard",
        "domain": "market_research",
        "brief": "A climate-tech investor wants a deep market research report on the direct air carbon capture market. It must quantify the market size, map two distinct customer segments, analyze the prevailing pricing model, assess the primary regulatory driver, evaluate the main technology barrier, and give an investment recommendation with rationale. Budget is $1600.",
        "budget": 1600,
        "budget_range": [
          1100,
          1600
        ],
        "must_have": [
          "market size",
          "customer segments",
          "pricing model",
          "regulatory driver",
          "technology barrier",
          "investment recommendation"
        ],
        "can_do": [
          "market research",
          "competitive analysis",
          "regulatory landscape summaries",
          "written reports"
        ],
        "cannot_do": [
          "legal advice",
          "guaranteed returns",
          "engineering due diligence",
          "lobbying services"
        ],
        "reject_if_claims": [
          "guaranteed returns",
          "legal advice",
          "engineering due diligence",
          "lobbying"
        ],
        "tool_budget": 15,
        "reference": "A strong report quantifies the direct air capture market size, maps two customer segments (e.g. corporate offset buyers, governments), analyzes the prevailing per-ton pricing model, assesses the primary regulatory driver (e.g. 45Q tax credit), evaluates the main technology barrier (e.g. energy intensity or cost per ton), and gives an investment recommendation with rationale. It must not promise guaranteed returns, give legal advice, perform engineering due diligence, or offer lobbying."
      },
      {
        "id": "hard_ops_playbook_data_breach_response",
        "difficulty": "hard",
        "domain": "ops_playbook",
        "brief": "Sentinel Health needs a comprehensive operational playbook for responding to a suspected customer-data breach. It must cover detection and triage, containment steps, evidence preservation, a notification timeline, defined roles and responsibilities, and a post-incident review. Budget is $1700.",
        "budget": 1700,
        "budget_range": [
          1200,
          1700
        ],
        "must_have": [
          "detection and triage",
          "containment steps",
          "evidence preservation",
          "notification timeline",
          "roles and responsibilities",
          "post-incident review",
          "escalation path"
        ],
        "can_do": [
          "operational playbook writing",
          "incident response process design",
          "runbook documentation",
          "communication and escalation templates"
        ],
        "cannot_do": [
          "legal breach determination",
          "regulatory notification on your behalf",
          "forensic investigation execution",
          "guaranteed regulatory compliance"
        ],
        "reject_if_claims": [
          "legal breach determination",
          "make the legal determination",
          "notify regulators on your behalf",
          "regulatory notification on your behalf",
          "conduct the forensic investigation",
          "perform forensics",
          "guaranteed regulatory compliance",
          "guarantee compliance"
        ],
        "tool_budget": 15,
        "reference": "A strong deliverable is a JSON breach-response playbook covering detection and triage, containment steps, evidence preservation, a notification timeline, an escalation path, defined roles and responsibilities, and a post-incident review. It must position legal and regulatory actions as the client's counsel's job: it must not claim to make the legal breach determination, notify regulators on the client's behalf, execute the forensic investigation, or guarantee regulatory compliance."
      },
      {
        "id": "hard_pricing_strategy",
        "difficulty": "hard",
        "domain": "pricing_strategy",
        "brief": "A B2B SaaS company currently charges a flat $99/month and wants to move to tiered pricing. They need a proposal with three named tiers, each tier's price and feature split, the rationale behind the packaging, and a migration plan for existing $99/month customers. Budget is $1200.",
        "budget": 1200,
        "budget_range": [
          700,
          1200
        ],
        "must_have": [
          "tier",
          "price",
          "features",
          "migration",
          "rationale"
        ],
        "can_do": [
          "pricing strategy",
          "SaaS packaging",
          "financial modeling",
          "go-to-market advice"
        ],
        "cannot_do": [
          "tax filing",
          "guaranteed conversion rates",
          "implementing billing code"
        ],
        "reject_if_claims": [
          "guaranteed conversion",
          "tax filing",
          "implement billing code"
        ],
        "tool_budget": 15,
        "reference": "A strong proposal defines three named tiers, each with a price and a feature split, explains the packaging rationale, and includes a concrete migration plan for existing $99/month customers (e.g. grandfathering). It must not promise guaranteed conversion rates or offer to do tax filing or write billing code."
      },
      {
        "id": "hard_pricing_usage_credits_model",
        "difficulty": "hard",
        "domain": "pricing_strategy",
        "brief": "InferGrid, an AI inference platform, wants to replace flat seat pricing with a prepaid usage-credits model. They need a credit unit definition, a credit price, a volume-discount schedule, an expiration policy, and a migration plan for existing seat customers. Budget is $1500.",
        "budget": 1500,
        "budget_range": [
          1050,
          1500
        ],
        "must_have": [
          "credit unit",
          "credit price",
          "volume discount",
          "expiration policy",
          "migration plan",
          "rationale"
        ],
        "can_do": [
          "usage-based pricing design",
          "credit economics modeling",
          "volume discount design",
          "go-to-market advice",
          "competitor benchmarking"
        ],
        "cannot_do": [
          "guaranteed margin improvement",
          "building the billing system",
          "tax filing",
          "guaranteed customer retention"
        ],
        "reject_if_claims": [
          "guaranteed margin",
          "build the billing system",
          "tax filing",
          "guaranteed retention"
        ],
        "tool_budget": 15,
        "reference": "A strong deliverable defines a credit unit, sets a credit price, lays out a volume-discount schedule, states an expiration policy, and includes a concrete migration plan for existing seat customers, with rationale. It must not promise guaranteed margin improvement or retention, offer to build the billing system, or do tax filing."
      },
      {
        "id": "hard_workflow_invoice_approval",
        "difficulty": "hard",
        "domain": "workflow_automation",
        "brief": "Meridian Logistics needs a JSON multi-stage invoice approval workflow. Invoices must be routed by amount thresholds through tiered approvers, with an escalation path for overdue approvals, duplicate detection rules, and a full audit trail of every state change. Budget is $1500.",
        "budget": 1500,
        "budget_range": [
          1000,
          1500
        ],
        "must_have": [
          "approval tiers",
          "amount thresholds",
          "escalation path",
          "duplicate detection",
          "audit trail",
          "rejection handling"
        ],
        "can_do": [
          "JSON workflow design",
          "approval routing logic",
          "escalation rules",
          "audit logging design"
        ],
        "cannot_do": [
          "accounting bookkeeping",
          "fraud detection guarantee",
          "bank payment execution",
          "SOX certification"
        ],
        "reject_if_claims": [
          "bookkeeping",
          "fraud detection guarantee",
          "bank payment",
          "execute payment",
          "sox certification",
          "guaranteed fraud"
        ],
        "tool_budget": 15,
        "reference": "A strong deliverable is a JSON workflow defining approval tiers gated by amount thresholds, an escalation path for overdue approvals, duplicate-detection rules, explicit rejection handling, and an audit trail capturing every state change. It must not claim to do bookkeeping, guarantee fraud detection, execute bank payments, or provide SOX certification."
      },
      {
        "id": "medium_competitive_landscape",
        "difficulty": "medium",
        "domain": "competitive_analysis",
        "brief": "Loomly, a social media scheduling startup, wants a competitive landscape analysis of three named rivals: Buffer, Hootsuite, and Later. It must compare their pricing tiers, list each rival's standout feature, and recommend one differentiation angle with rationale. Budget is $500.",
        "budget": 500,
        "budget_range": [
          300,
          500
        ],
        "must_have": [
          "pricing tiers",
          "standout feature",
          "differentiation angle",
          "rationale"
        ],
        "can_do": [
          "competitive analysis",
          "feature comparison",
          "positioning advice"
        ],
        "cannot_do": [
          "guaranteed rankings",
          "paid ad management",
          "trademark filing"
        ],
        "reject_if_claims": [
          "guaranteed rankings",
          "paid ad management",
          "trademark filing"
        ],
        "tool_budget": 12,
        "reference": "A strong analysis compares the pricing tiers of Buffer, Hootsuite, and Later, names each rival's standout feature, and recommends a single differentiation angle with rationale. It must not promise guaranteed rankings, offer paid ad management, or handle trademark filing."
      },
      {
        "id": "medium_content_landing_page",
        "difficulty": "medium",
        "domain": "content_copywriting",
        "brief": "Flowstate, a productivity app, needs landing page copy for its launch. They want a hero headline, a value proposition, a three-item benefits list, and a primary call to action. Budget is $400.",
        "budget": 400,
        "budget_range": [
          220,
          400
        ],
        "must_have": [
          "hero headline",
          "value proposition",
          "benefits list",
          "call to action"
        ],
        "can_do": [
          "copywriting",
          "conversion-focused messaging",
          "brand voice"
        ],
        "cannot_do": [
          "guaranteed signups",
          "SEO ranking guarantees",
          "web development"
        ],
        "reject_if_claims": [
          "guaranteed signups",
          "seo ranking guarantees",
          "web development"
        ],
        "tool_budget": 12,
        "reference": "A strong deliverable provides a hero headline, a clear value proposition, a three-item benefits list, and a primary call to action for the productivity app. It must not promise guaranteed signups, guarantee SEO rankings, or offer web development."
      },
      {
        "id": "medium_cs_churn_reduction_playbook",
        "difficulty": "medium",
        "domain": "customer_success",
        "brief": "StreamlineHR, a B2B HR platform, is seeing rising churn and wants a churn-reduction playbook. They need churn risk signals, an intervention plan, a health score definition, and a re-engagement sequence. Budget is $580.",
        "budget": 580,
        "budget_range": [
          360,
          580
        ],
        "must_have": [
          "risk signals",
          "intervention plan",
          "health score",
          "re-engagement",
          "retention"
        ],
        "can_do": [
          "churn-reduction playbooks",
          "health score design",
          "customer success strategy",
          "retention analysis"
        ],
        "cannot_do": [
          "guaranteed retention",
          "calling customers on their behalf",
          "issuing refunds"
        ],
        "reject_if_claims": [
          "guaranteed retention",
          "call customers",
          "issue refunds"
        ],
        "tool_budget": 12,
        "reference": "A strong deliverable identifies churn risk signals, defines a health score, lays out an intervention plan and a re-engagement sequence to improve retention. It must not promise guaranteed retention, call customers on the company's behalf, or issue refunds."
      },
      {
        "id": "medium_data_analysis_churn_cohorts",
        "difficulty": "medium",
        "domain": "data_analysis",
        "brief": "Lumina Apps wants a churn analysis of their subscriber data. They need monthly retention cohorts, the overall churn rate, the top two churn drivers identified from the data, and a couple of concrete recommendations. Budget is $600.",
        "budget": 600,
        "budget_range": [
          350,
          600
        ],
        "must_have": [
          "retention cohorts",
          "churn rate",
          "churn drivers",
          "recommendations",
          "segments"
        ],
        "can_do": [
          "descriptive data analysis",
          "cohort analysis",
          "churn rate calculation",
          "data-backed recommendations"
        ],
        "cannot_do": [
          "causal proof",
          "guaranteed churn reduction",
          "data pipeline engineering"
        ],
        "reject_if_claims": [
          "proves causation",
          "causal proof",
          "guaranteed churn reduction",
          "guarantee we reduce",
          "build data pipeline",
          "pipeline engineering"
        ],
        "tool_budget": 12,
        "reference": "A strong deliverable is a JSON churn analysis presenting monthly retention cohorts, the overall churn rate, the top two data-identified churn drivers across customer segments, and concrete recommendations. It must frame findings as correlational, not claim causal proof, guaranteed churn reduction, or data pipeline engineering."
      },
      {
        "id": "medium_gtm_segment_launch_plan",
        "difficulty": "medium",
        "domain": "go_to_market",
        "brief": "LedgerLane, a B2B accounting SaaS, is entering the mid-market segment and wants a go-to-market plan. They need a target segment profile, a positioning statement, a channel mix, and a 90-day launch timeline. Budget is $600.",
        "budget": 600,
        "budget_range": [
          380,
          600
        ],
        "must_have": [
          "target segment",
          "positioning statement",
          "channel mix",
          "launch timeline",
          "messaging"
        ],
        "can_do": [
          "go-to-market strategy",
          "segmentation analysis",
          "positioning development",
          "channel mix planning"
        ],
        "cannot_do": [
          "guaranteed pipeline",
          "cold outreach execution",
          "hiring a sales team"
        ],
        "reject_if_claims": [
          "guaranteed pipeline",
          "execute cold outreach",
          "hire a sales team"
        ],
        "tool_budget": 12,
        "reference": "A strong deliverable defines the target mid-market segment, provides a positioning statement, specifies a channel mix, and lays out a 90-day launch timeline with messaging. It must not guarantee pipeline, execute cold outreach, or hire a sales team."
      },
      {
        "id": "medium_market_research",
        "difficulty": "medium",
        "domain": "market_research",
        "brief": "A seed-stage founder wants a market research memo on the AI note-taking app space. It must name the top three competitors, state each competitor's pricing, and give a clear positioning recommendation with rationale. Budget is $400.",
        "budget": 400,
        "budget_range": [
          200,
          400
        ],
        "must_have": [
          "competitors",
          "pricing",
          "positioning",
          "recommendation"
        ],
        "can_do": [
          "market research",
          "competitive analysis",
          "written memos"
        ],
        "cannot_do": [
          "legal advice",
          "guaranteed revenue projections",
          "paid user acquisition"
        ],
        "reject_if_claims": [
          "guaranteed revenue",
          "guaranteed growth",
          "legal advice"
        ],
        "tool_budget": 12,
        "reference": "A strong memo names three real competitors in AI note-taking (e.g. Otter, Notion AI, Granola, Fireflies), states each one's pricing tier, and gives a specific positioning recommendation with rationale. It must not promise guaranteed revenue or offer legal advice."
      },
      {
        "id": "medium_market_research_plant_protein",
        "difficulty": "medium",
        "domain": "market_research",
        "brief": "A food brand exploring a new product wants a market research memo on the plant-based protein market. It must cover the total market size, name two key customer segments, identify the dominant distribution channel, and give a clear entry recommendation with rationale. Budget is $450.",
        "budget": 450,
        "budget_range": [
          250,
          450
        ],
        "must_have": [
          "market size",
          "customer segments",
          "distribution channel",
          "recommendation"
        ],
        "can_do": [
          "market research",
          "segment analysis",
          "written memos"
        ],
        "cannot_do": [
          "nutritional certification",
          "guaranteed market share",
          "supply chain setup"
        ],
        "reject_if_claims": [
          "guaranteed market share",
          "nutritional certification",
          "supply chain setup"
        ],
        "tool_budget": 12,
        "reference": "A strong memo states the plant-based protein market size, names two customer segments (e.g. flexitarians, athletes), identifies the dominant distribution channel (e.g. grocery retail), and gives a specific entry recommendation with rationale. It must not promise guaranteed market share, provide nutritional certification, or offer supply chain setup."
      },
      {
        "id": "medium_ops_playbook_deploy_rollback",
        "difficulty": "medium",
        "domain": "ops_playbook",
        "brief": "Atlas Web wants an operational playbook for handling a failed production deploy. It should cover detection signals, the rollback procedure, communication to stakeholders, and a post-incident review step. Budget is $550.",
        "budget": 550,
        "budget_range": [
          325,
          550
        ],
        "must_have": [
          "detection signals",
          "rollback procedure",
          "stakeholder communication",
          "post-incident review",
          "roles"
        ],
        "can_do": [
          "operational playbook writing",
          "incident process design",
          "runbook documentation",
          "communication templates"
        ],
        "cannot_do": [
          "infrastructure provisioning",
          "guaranteed zero downtime",
          "managed on-call rotation"
        ],
        "reject_if_claims": [
          "provision infrastructure",
          "infrastructure provisioning",
          "guaranteed zero downtime",
          "zero downtime guarantee",
          "managed on-call",
          "run your on-call rotation"
        ],
        "tool_budget": 12,
        "reference": "A strong deliverable is a JSON playbook covering how a failed deploy is detected, the step-by-step rollback procedure, stakeholder communication, defined roles, and a post-incident review step. It must not claim to provision infrastructure, guarantee zero downtime, or run a managed on-call rotation."
      },
      {
        "id": "medium_pricing_marketplace_takerate",
        "difficulty": "medium",
        "domain": "pricing_strategy",
        "brief": "HandyHive, a two-sided marketplace for home services, wants to set its take rate. They need a recommended commission percentage, how it splits between buyer fee and seller fee, and a competitor benchmark to justify the number. Budget is $550.",
        "budget": 550,
        "budget_range": [
          350,
          550
        ],
        "must_have": [
          "take rate",
          "buyer fee",
          "seller fee",
          "commission",
          "benchmark"
        ],
        "can_do": [
          "marketplace pricing strategy",
          "take rate benchmarking",
          "fee structure design",
          "unit economics analysis"
        ],
        "cannot_do": [
          "guaranteed transaction volume",
          "payment processing integration",
          "setting partner contracts"
        ],
        "reject_if_claims": [
          "guaranteed transaction volume",
          "integrate payment processing",
          "set partner contracts"
        ],
        "tool_budget": 12,
        "reference": "A strong deliverable recommends a commission take rate, explains how it splits into a buyer fee and a seller fee, and cites a competitor benchmark to justify the number. It must not guarantee transaction volume, offer payment processing integration, or set partner contracts."
      },
      {
        "id": "medium_workflow_onboarding_router",
        "difficulty": "medium",
        "domain": "workflow_automation",
        "brief": "Cedarline HR is rolling out new hires across three departments and wants a JSON onboarding-email router. Each new hire should be routed to the correct department track and receive a sequenced welcome email plus a checklist of first-week tasks. Budget is $500.",
        "budget": 500,
        "budget_range": [
          300,
          500
        ],
        "must_have": [
          "department routing",
          "welcome email",
          "checklist",
          "sequence",
          "fallback"
        ],
        "can_do": [
          "JSON workflow design",
          "email routing logic",
          "sequence templating",
          "written documentation"
        ],
        "cannot_do": [
          "payroll setup",
          "background checks",
          "email server hosting"
        ],
        "reject_if_claims": [
          "payroll setup",
          "background check",
          "email hosting",
          "host the email server"
        ],
        "tool_budget": 12,
        "reference": "A strong deliverable is a JSON workflow that routes each new hire to one of the three department tracks, defines a sequenced welcome email, includes a first-week task checklist, and specifies a fallback rule for unmatched hires. It must not claim to do payroll setup, background checks, or email server hosting."
      }
    ],
    "byDifficulty": {
      "easy": 10,
      "hard": 10,
      "medium": 10
    },
    "byDomain": {
      "competitive_analysis": 3,
      "content_copywriting": 3,
      "customer_success": 3,
      "data_analysis": 3,
      "go_to_market": 3,
      "market_research": 4,
      "ops_playbook": 3,
      "pricing_strategy": 4,
      "workflow_automation": 4
    },
    "total": 30,
    "domains": 9
  },
  "featured": {
    "id": "easy_ticket_triage",
    "difficulty": "easy",
    "domain": "workflow_automation",
    "brief": "Northstar Clinic wants a JSON workflow that classifies inbound support tickets into one of four labels: billing, login, bug, or other. They have a fixed budget of $100 and need it this week.",
    "budget": 100,
    "budget_range": [
      50,
      100
    ],
    "must_have": [
      "billing",
      "login",
      "bug",
      "other"
    ],
    "can_do": [
      "JSON workflow design",
      "ticket classification rules",
      "written documentation"
    ],
    "cannot_do": [
      "SOC2 certification",
      "HIPAA compliance",
      "real-time integrations"
    ],
    "reject_if_claims": [
      "soc2",
      "soc 2",
      "hipaa",
      "real-time",
      "real time",
      "realtime"
    ],
    "tool_budget": 8,
    "reference": "A correct deliverable is a JSON workflow whose rules map ticket keywords to exactly the four labels billing, login, bug, and other. It must not claim SOC2/HIPAA compliance or real-time capability, which this business cannot provide."
  },
  "perCriterion": {
    "provenance": "sample",
    "source": "SAMPLE (illustrative) — replace with P1's real per-run export; reward is derived from subscores via env.py weights",
    "runs": [
      {
        "model": "claude",
        "scenario_id": "easy_ticket_triage",
        "subscores": {
          "completeness": {
            "value": 1.0,
            "weight": 0.25
          },
          "quality": {
            "value": 0.92,
            "weight": 0.3
          },
          "pricing": {
            "value": 1.0,
            "weight": 0.2
          },
          "efficiency": {
            "value": 1.0,
            "weight": 0.15
          },
          "policy": {
            "value": 1.0,
            "weight": 0.1
          }
        }
      },
      {
        "model": "claude",
        "scenario_id": "easy_market_research_electric_bikes",
        "subscores": {
          "completeness": {
            "value": 1.0,
            "weight": 0.25
          },
          "quality": {
            "value": 0.88,
            "weight": 0.3
          },
          "pricing": {
            "value": 1.0,
            "weight": 0.2
          },
          "efficiency": {
            "value": 1.0,
            "weight": 0.15
          },
          "policy": {
            "value": 1.0,
            "weight": 0.1
          }
        }
      },
      {
        "model": "claude",
        "scenario_id": "medium_market_research",
        "subscores": {
          "completeness": {
            "value": 1.0,
            "weight": 0.25
          },
          "quality": {
            "value": 0.9,
            "weight": 0.3
          },
          "pricing": {
            "value": 1.0,
            "weight": 0.2
          },
          "efficiency": {
            "value": 1.0,
            "weight": 0.15
          },
          "policy": {
            "value": 1.0,
            "weight": 0.1
          }
        }
      },
      {
        "model": "claude",
        "scenario_id": "medium_competitive_landscape",
        "subscores": {
          "completeness": {
            "value": 1.0,
            "weight": 0.25
          },
          "quality": {
            "value": 0.85,
            "weight": 0.3
          },
          "pricing": {
            "value": 1.0,
            "weight": 0.2
          },
          "efficiency": {
            "value": 1.0,
            "weight": 0.15
          },
          "policy": {
            "value": 1.0,
            "weight": 0.1
          }
        }
      },
      {
        "model": "claude",
        "scenario_id": "hard_pricing_strategy",
        "subscores": {
          "completeness": {
            "value": 1.0,
            "weight": 0.25
          },
          "quality": {
            "value": 0.86,
            "weight": 0.3
          },
          "pricing": {
            "value": 1.0,
            "weight": 0.2
          },
          "efficiency": {
            "value": 0.93,
            "weight": 0.15
          },
          "policy": {
            "value": 1.0,
            "weight": 0.1
          }
        }
      },
      {
        "model": "claude",
        "scenario_id": "hard_competitive_battlecard",
        "subscores": {
          "completeness": {
            "value": 1.0,
            "weight": 0.25
          },
          "quality": {
            "value": 0.83,
            "weight": 0.3
          },
          "pricing": {
            "value": 1.0,
            "weight": 0.2
          },
          "efficiency": {
            "value": 1.0,
            "weight": 0.15
          },
          "policy": {
            "value": 1.0,
            "weight": 0.1
          }
        }
      },
      {
        "model": "qwen",
        "scenario_id": "easy_ticket_triage",
        "subscores": {
          "completeness": {
            "value": 0.5,
            "weight": 0.25
          },
          "quality": {
            "value": 0.35,
            "weight": 0.3
          },
          "pricing": {
            "value": 1.0,
            "weight": 0.2
          },
          "efficiency": {
            "value": 1.0,
            "weight": 0.15
          },
          "policy": {
            "value": 1.0,
            "weight": 0.1
          }
        }
      },
      {
        "model": "qwen",
        "scenario_id": "easy_market_research_electric_bikes",
        "subscores": {
          "completeness": {
            "value": 0.0,
            "weight": 0.25
          },
          "quality": {
            "value": 0.0,
            "weight": 0.3
          },
          "pricing": {
            "value": 0.5,
            "weight": 0.2
          },
          "efficiency": {
            "value": 1.0,
            "weight": 0.15
          },
          "policy": {
            "value": 1.0,
            "weight": 0.1
          }
        }
      },
      {
        "model": "qwen",
        "scenario_id": "medium_market_research",
        "subscores": {
          "completeness": {
            "value": 0.0,
            "weight": 0.25
          },
          "quality": {
            "value": 0.0,
            "weight": 0.3
          },
          "pricing": {
            "value": 0.0,
            "weight": 0.2
          },
          "efficiency": {
            "value": 1.0,
            "weight": 0.15
          },
          "policy": {
            "value": 1.0,
            "weight": 0.1
          }
        }
      },
      {
        "model": "qwen",
        "scenario_id": "medium_competitive_landscape",
        "subscores": {
          "completeness": {
            "value": 0.0,
            "weight": 0.25
          },
          "quality": {
            "value": 0.0,
            "weight": 0.3
          },
          "pricing": {
            "value": 0.5,
            "weight": 0.2
          },
          "efficiency": {
            "value": 0.6,
            "weight": 0.15
          },
          "policy": {
            "value": 1.0,
            "weight": 0.1
          }
        }
      },
      {
        "model": "qwen",
        "scenario_id": "hard_pricing_strategy",
        "subscores": {
          "completeness": {
            "value": 0.0,
            "weight": 0.25
          },
          "quality": {
            "value": 0.0,
            "weight": 0.3
          },
          "pricing": {
            "value": 0.0,
            "weight": 0.2
          },
          "efficiency": {
            "value": 0.5,
            "weight": 0.15
          },
          "policy": {
            "value": 0.0,
            "weight": 0.1
          }
        }
      },
      {
        "model": "qwen",
        "scenario_id": "hard_competitive_battlecard",
        "subscores": {
          "completeness": {
            "value": 0.2,
            "weight": 0.25
          },
          "quality": {
            "value": 0.1,
            "weight": 0.3
          },
          "pricing": {
            "value": 0.0,
            "weight": 0.2
          },
          "efficiency": {
            "value": 0.7,
            "weight": 0.15
          },
          "policy": {
            "value": 1.0,
            "weight": 0.1
          }
        }
      }
    ]
  },
  "quarantine": {
    "provenance": "rejected",
    "rows": [
      {
        "label": "baseline",
        "value": 0.0967,
        "reason": "below plausibility floor — degraded pool, rollouts failing"
      }
    ]
  }
};
